apiVersion: networking.istio.io/v1alpha3
kind: EnvoyFilter
metadata:
  name: gofilter
spec:
  workloadSelector:
    labels:
      app: echo-server
  configPatches:
  - applyTo: HTTP_FILTER
    match:
      context: SIDECAR_INBOUND
      listener:
        portNumber: 9000
        filterChain:
          filter:
            name: "envoy.filters.network.http_connection_manager"
            subFilter:
              name: "envoy.filters.http.router"
    patch:
      operation: INSERT_BEFORE
      value: 
        name: envoy.filters.http.golang
        typed_config:
          "@type": type.googleapis.com/envoy.extensions.filters.http.golang.v3alpha.Config
          library_id: my-plugin-id
          library_path: "/etc/libgolang.so"
          plugin_name: my_plugin